### ISSUE TITLE
`repositories` key is not a valid configuration for release events

### ISSUE THREAD

**Issue by galligan** [galligan/github-markdown-tailwindcss#3]
_:warning: Potential issue_

**Fix invalid workflow trigger configuration.**

The `repositories` key is not a valid configuration for release events. To watch releases from external repositories, you need to use repository dispatch events.

Replace the current trigger with:

```diff
-on:
-  release:
-    types: [published]
-    repositories:
-      - sindresorhus/github-markdown-css
+on:
+  repository_dispatch:
+    types: [github-markdown-css-release]
```

Then create a separate workflow to watch the external repository:

```yaml
name: Watch External Release

on:
  schedule:
    - cron: '0 */6 * * *'  # Check every 6 hours

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/sindresorhus/github-markdown-css/releases/latest)
          latest_tag=$(echo $latest_release | jq -r .tag_name)
          current_tag=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name || echo "none")
          if [ "$latest_tag" != "$current_tag" ]; then
            curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{"event_type":"github-markdown-css-release"}'
          fi
```

<details>
<summary>🧰 Tools</summary>

<details>
<summary>🪛 actionlint (1.7.4)</summary>

6-6: unexpected key "repositories" for "release" section. expected one of "branches", "branches-ignore", "paths", "paths-ignore", "tags", "tags-ignore", "types", "workflows"

(syntax-check)

</details>

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/galligan/github-markdown-tailwindcss/pull/2#discussion_r1931227167_
